print("Welcome to the Madlibs App!\nEnter your words and they will be added to the story:")
listWords = list()
listWords.insert(0, input('body organ: '))
listWords.insert(1, input('adjective: '))
listWords.insert(2, input('verb: '))
listWords.insert(3, input('plural noun: '))
listWords.insert(4, input('plural noun: '))
listWords.insert(5, input('plural noun: '))
listWords.insert(6, input('adjective: '))
listWords.insert(7, input('adjective: '))
listWords.insert(8, input('plural noun: '))
listWords.insert(9, input('container: '))
listWords.insert(10, input('adjective: '))
listWords.insert(11, input('noun: '))
listWords.insert(12, input('adjective: '))
listWords.insert(13, input('adjective: '))
listWords.insert(14, input('number: '))
listWords.insert(15, input('adjective: '))
listWords.insert(16, input('adverb: '))
listWords.insert(17, input('noun: '))
listWords.insert(18, input('verb: '))
listWords.insert(19, input('adjective: '))
listWords.insert(20, input('event: '))
listWords.insert(21, input('verb: '))
listWords.insert(22, input('adjective: '))
listWords.insert(23, input('exclamation: '))
text = "Have you heard of", listWords[0], "storming? \n", chr(124), "Many say that it is", listWords[1], "and does not", listWords[2], "\b. \n", chr(124), "However, with the combination of the right", listWords[3], "\b,", listWords[4], "\b, and", listWords[5], "\n", chr(124), "anyone can lead a", listWords[6], "session. \n", chr(124), "When you have pulled together a", listWords[7], "group of", listWords[8], "brought together \n", chr(124), "in a", listWords[9], "that is", listWords[10], "and have a", listWords[11], "that is", listWords[12], "for the \n", chr(124), "participants to suggest", listWords[13], "ideas, you will yield", listWords[14], "more", listWords[15], "ideas. \n", chr(124), "Next time you need", listWords[16], "thought-up ideas for a", listWords[17], "\b, \n", chr(124), "a way to", listWords[18], "sales for your business, or even", listWords[19], "ideas for activities for \n", chr(124), "the company", listWords[20], "put these suggestions to work and let the ideas", listWords[21], "\b. \n", chr(124), "With so many", listWords[22], "ideas you'll have the boss declaring", listWords[23], "in no time!\n", chr(124), "Credit for story: \n", chr(124), "https://idea-sandbox.com/blog/better-brainstorming-mad-lib/"